// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPM9tTNew4L0zzVJ7dvgU2tVMrb97SKJA',
    appId: '1:839251073756:web:f2c850c0f0cb98424cb219',
    messagingSenderId: '839251073756',
    projectId: 'project-itds283-mobile-47f43',
    authDomain: 'project-itds283-mobile-47f43.firebaseapp.com',
    storageBucket: 'project-itds283-mobile-47f43.firebasestorage.app',
    measurementId: 'G-5PTEPBZK0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnBxQO6ewchsmDLt3EFhBZssKjsoVRoqk',
    appId: '1:839251073756:android:22d5a0363963aa434cb219',
    messagingSenderId: '839251073756',
    projectId: 'project-itds283-mobile-47f43',
    storageBucket: 'project-itds283-mobile-47f43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdXB2287cJEHKq8sLPk33fGZe9ZAXAcjk',
    appId: '1:839251073756:ios:a1140abffff625bc4cb219',
    messagingSenderId: '839251073756',
    projectId: 'project-itds283-mobile-47f43',
    storageBucket: 'project-itds283-mobile-47f43.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdXB2287cJEHKq8sLPk33fGZe9ZAXAcjk',
    appId: '1:839251073756:ios:a1140abffff625bc4cb219',
    messagingSenderId: '839251073756',
    projectId: 'project-itds283-mobile-47f43',
    storageBucket: 'project-itds283-mobile-47f43.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPM9tTNew4L0zzVJ7dvgU2tVMrb97SKJA',
    appId: '1:839251073756:web:24d8d7e3647d171b4cb219',
    messagingSenderId: '839251073756',
    projectId: 'project-itds283-mobile-47f43',
    authDomain: 'project-itds283-mobile-47f43.firebaseapp.com',
    storageBucket: 'project-itds283-mobile-47f43.firebasestorage.app',
    measurementId: 'G-JK12VZBDWK',
  );
}
